#!/usr/bin/env python3
"""Clone gren-format compiler repos into the current working directory."""

import subprocess

NON_CORE_REPOS = [
    "https://github.com/gilramir/gren-format.git",
    "https://github.com/gilramir/gren-format-lib.git",
]

CORE_REPOS = [
]


def repo_name(url):
    return url.removesuffix(".git").rsplit("/", 1)[-1]


def clone_and_configure(url, is_core):
    name = repo_name(url)
    print(f"Cloning {url} ...")
    subprocess.run(["git", "clone", url, name], check=True)
    if is_core:
        print("  Checking out formatter branch")
        subprocess.run(
            ["git", "-C", name, "checkout", "formatter"],
            check=True,
        )
    else:
        print("  Checking out like-elm-format branch")
        subprocess.run(
            ["git", "-C", name, "checkout", "like-elm-format"],
            check=True,
        )


def main() -> None:
    for url in NON_CORE_REPOS:
        clone_and_configure(url, is_core=False)
    for url in CORE_REPOS:
        clone_and_configure(url, is_core=True)

    print("\nDone.")


if __name__ == "__main__":
    main()
